# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Process'), (2, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low priority'), (2, 'Normal priority'), (1, 'Top Priority')], default=2),
        ),
    ]
